### ISSUE TITLE
Number of nears in wallet and nearnames does not match

### ISSUE THREAD

**Issue by Svyatoslav-Kasatov** [galactic3/nearnames#29]
![image](https://user-images.githubusercontent.com/58220092/150209263-c6a60f2e-f320-4afb-af02-bdde704544ca.png)
![image](https://user-images.githubusercontent.com/58220092/150209288-8e0eda5f-504e-45dd-a514-b4274f739405.png)

**Comment by alexaunter** [comment]
Root cause: wallet shows available balance, while we show total balance. Not an issue.
